### ISSUE TITLE
Feature Request: Turn this into a cookiecutter template

### ISSUE THREAD

**Issue by andrewthetechie** [rszamszur/fastapi-mvc#6]
This seems like a solid Fastapi template. Any chance you might want to set it up as a cookiecutter template? https://cookiecutter.readthedocs.io/en/1.7.2/

**Comment by rszamszur** [comment]
Definitely! I was planing some kind of generator for the next release. I haven't yet figured out exactly how I want to implement this, but it'll be using a cookie-cutter template underneath. I guess a CLI, which will be an entry point to all actions on the template (new, serve, test, etc). And then I'll probably publish this package to PyPI as well.

**Comment by rszamszur** [comment]
@andrewthetechie final release is yet to be done, but the cookie-cutter template is ready and the prerelease package is in PyPI.

### Install

```shell
pip install fastapi-mvc
```

### Generate project
```shell
# Example
# name or path
fastapi-mvc new foobar

# Usage
Usage: fastapi-mvc new [OPTIONS] APP_PATH

  Create a new FastAPI application.

  The 'fastapi-mvc new' command creates a new FastAPI application with a
  default directory structure and configuration at the path you specify.

Options:
  -R, --skip-redis                Skip Redis utility files.
  -A, --skip-aiohttp              Skip aiohttp utility files.
  -V, --skip-vagrantfile          Skip Vagrantfile.
  -H, --skip-helm                 Skip Helm chart files.
  -G, --skip-actions              Skip GitHub actions files.
  -C, --skip-codecov              Skip codecov in GitHub actions.
  -I, --skip-install              Dont run make install
  --license [MIT|BSD2|BSD3|ISC|Apache2.0|LGPLv3+|LGPLv3|LGPLv2+|LGPLv2|no]
                                  Choose license.  [default: MIT]
  --repo-url TEXT                 Repository url.
  --help                          Show this message and exit.

```

[Example generated project with full configuration](https://github.com/rszamszur/fastapi-mvc-example)

**Comment by andrewthetechie** [comment]
very cool!
