### ISSUE TITLE
Installation fails on Python 3.10+

### ISSUE THREAD

**Issue by Merinorus** [rszamszur/fastapi-mvc#60]
- [x] I have searched the [issues](https://github.com/rszamszur/fastapi-mvc/issues) of this repo and believe that this is not a duplicate.

**Describe the bug**
I cannot use `make install` with Python 3.10. The installation fails because "Python version is less than 3.7".

**Expected behavior**
It should install correctly with Python 3.10.

**To Reproduce**

**Environment**
* Python version: 3.10.4
* Operating System and version: Ubuntu 20.04 LTS (WSL 2)
* fastapi-mvc version: 0.9.0

**Comment by rszamszur** [comment]
I knew comparing semver strings in bash was too good to be true :smile:
